# Training configuration for Penalty Shootout RL

training:
  num_episodes: 1000
  max_steps: 1000
  save_interval: 100
  log_interval: 10
  eval_interval: 50
  num_eval_episodes: 10

# Agent configurations
striker:
  policy: 'MlpPolicy'
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  policy_kwargs:
    net_arch: [dict(pi=[64, 64], vf=[64, 64])]
    activation_fn: 'relu'

goalkeeper:
  policy: 'MlpPolicy'
  learning_rate: 1e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  policy_kwargs:
    net_arch: [dict(pi=[64, 64], vf=[64, 64])]
    activation_fn: 'tanh'
